### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by Pelti148** [KageJittai/FoundryVTT-FiveTorchesDeep-System#15]
Hey, I am pretty new to all of this, but it seems like the link doesn't work when I try to put it into the Manifest URL, it gives me the following error:
"installation failed: unable to load valid system manifest data"

**Comment by KageJittai** [comment]
Make sure you using this link for the manifest:

https://raw.githubusercontent.com/KageJittai/FoundryVTT-FiveTorchesDeep-System/main/system.json
