### ISSUE TITLE
Bug - An actor's Token Settings reset on reload/restart

### ISSUE THREAD

**Issue by MaebaeLmao** [KageJittai/FoundryVTT-FiveTorchesDeep-System#8]
The token name, appearance, resources etc. all reset to default upon restart.

**Comment by KageJittai** [comment]
Can you provide reproduction steps?

**Comment by MaebaeLmao** [comment]
Yes. If I have an actor in my directory and change their token information (Like their name, how they display their HP or their size) it will save and I can drag them into any scene I want with those changes no problem.

While that specific token will stay the same upon restart or reload, If i restart the token will be back to the default setting If I drag in a new one.

**Comment by KageJittai** [comment]
Tested this on the foundry 5e system. It's an issue with core foundry.
